from django.urls import path
from . import views


urlpatterns = [
    path('', views.index),
    path('home/', views.home, name='home'),
    # path('about/', views.about, name='about'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.register_view, name='register'),
    path('drafts/', views.drafts, name='drafts'),
    path('leagues/', views.leagues, name='leagues'),
    path('createLeague/', views.createLeague, name='createLeague'),
    path('updateLeague/<str:pk>/', views.updateLeague, name='updateLeague'),
    path('deleteLeague/<str:pk>/', views.deleteLeague, name='deleteLeague'),
    path('updateTeam/<str:pk>/', views.updateTeam, name='updateTeam'),
    path('updateMatch/<str:pk>/', views.updateMatch, name='updateMatch'),
    path('updateDraft/<str:pk>/', views.updateDraft, name='updateDraft'),
    path('updateTrade/<str:pk>/', views.updateTrade, name='updateTrade'),
    path('updateWaiver/<str:pk>/', views.updateWaiver, name='updateWaiver'),
    path('updatePlayer/<str:pk>/', views.updatePlayer, name='updatePlayer'),
    path('updatePlayerStatistic/<str:pk>/', views.updatePlayerStatistic, name='updatePlayerStatistic'),
    path('matches/', views.matches, name='matches'),
    path('match-teams/', views.match_teams, name='match_teams'),
    path('players/', views.players, name='players'),
    path('player_statistics/', views.player_statistics, name='player_statistics'),
    path('teams/', views.teams, name='teams'),
    path('createTeam/', views.createTeam, name='createTeam'),
    path('team-trades/', views.team_trades, name='team_trades'),
    path('team-waivers/', views.team_waivers, name='team_waivers'),
    path('trades/', views.trades, name='trades'),
    path('users/<int:pk_test>/', views.users, name='users'),
    path('waivers/', views.waivers, name='waivers'),
    # path('', views.dashboard, name='home'),  # 主页
    path('createDraft/', views.createDraft, name='createDraft'),
    path('createPlayer/', views.createPlayer, name='createPlayer'),
    path('createPlayerStatistics/', views.createPlayerStatistics, name='createPlayerStatistics'),
    path('createMatch/', views.createMatch, name='createMatch'),
    path('createTrade/', views.createTrade, name='createTrade'),
    path('createWaiver/', views.createWaiver, name='createWaiver'),
    path('deleteTeam/<int:pk>/', views.deleteTeam, name='deleteTeam'),
    path('deleteMatch/<str:pk>/', views.deleteMatch, name='deleteMatch'),
    path('deleteDraft/<str:pk>/', views.deleteDraft, name='deleteDraft'),
    path('deleteTrade/<str:pk>/', views.deleteTrade, name='deleteTrade'),
    path('deleteWaiver/<str:pk>/', views.deleteWaiver, name='deleteWaiver'),
    path('deletePlayer/<str:pk>/', views.deletePlayer, name='deletePlayer'),
    path('deletePlayerStatistics/<str:pk>/', views.deletePlayerStatistics, name='deletePlayerStatistics'),
    path('logs/', views.viewLogs, name='viewLogs'),
]