# Generated by Django 5.1.3 on 2024-12-01 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drafts',
            fields=[
                ('draft_id', models.AutoField(primary_key=True, serialize=False)),
                ('draftdate', models.DateField(blank=True, null=True)),
                ('draftorder', models.CharField(blank=True, max_length=1, null=True)),
                ('draftstatus', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'drafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('league_id', models.AutoField(primary_key=True, serialize=False)),
                ('leaguename', models.CharField(blank=True, max_length=30, null=True)),
                ('leaguetype', models.CharField(blank=True, max_length=1, null=True)),
                ('maxteams', models.DecimalField(decimal_places=0, max_digits=2)),
                ('draftdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leagues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('finalscore', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=3)),
                ('playerposition', models.CharField(blank=True, max_length=3, null=True)),
                ('realteam', models.CharField(blank=True, max_length=50, null=True)),
                ('fantasypoints', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('availabilitystatus', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playerstatistics',
            fields=[
                ('statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('gamedate', models.DateField(blank=True, null=True)),
                ('performancestats', models.TextField(blank=True, null=True)),
                ('injurystatus', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'playerstatistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=25)),
                ('totalpoints', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ranking', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('tradedate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waivers',
            fields=[
                ('waiver_id', models.AutoField(primary_key=True, serialize=False)),
                ('waiverorder', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('waiverstatus', models.CharField(blank=True, max_length=1, null=True)),
                ('waiverpickupdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matchteams',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mydjangoapp.matches')),
            ],
            options={
                'db_table': 'matchteams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamtrades',
            fields=[
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mydjangoapp.trades')),
            ],
            options={
                'db_table': 'teamtrades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamwaivers',
            fields=[
                ('waiver', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mydjangoapp.waivers')),
            ],
            options={
                'db_table': 'teamwaivers',
                'managed': False,
            },
        ),
    ]
